#!/bin/bash

k3d delete all

k3d create --port 443:443
sleep 30
export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
sleep 10

if [ "x$1" == "xcode" ]
then
  docker build -t robfielding/k3stest-frontend .
  docker push robfielding/k3stest-frontend
fi

helm uninstall k3st
helm install k3st ./k3st

# Generic ingress routing
kubectl apply -f kube/ingress.yaml
kubectl apply -f kube/traefik.yaml
sleep 10
kubectl -n kube-system scale deploy traefik --replicas 0
kubectl -n kube-system scale deploy traefik --replicas 1

kubectl get all
sleep 30
kubectl -n kube-system port-forward deployment/traefik 8080 &
