#!/bin/bash

export MYCLUSTER=gmd

k3d cluster delete $MYCLUSTER
k3d cluster create gmd --api-port 6999 --port 443:443@loadbalancer 
sleep 30
export KUBECONFIG="$(k3d get-kubeconfig --name=$MYCLUSTER)"
sleep 20

if [ "x$1" == "xcode" ]
then
  docker build -t robfielding/k3stest-frontend .
  docker push robfielding/k3stest-frontend
fi

helm uninstall k3st
helm install k3st ./k3st

# Generic ingress routing
kubectl apply -f kube/ingress.yaml
kubectl apply -f kube/traefik.yaml
sleep 30
kubectl -n kube-system scale deploy traefik --replicas 0
kubectl -n kube-system scale deploy traefik --replicas 1

kubectl get all
sleep 30
kubectl -n kube-system port-forward deployment/traefik 8080 &
