apiVersion: v1
kind: Pod
metadata:
  name: mongo-data
spec:
  volumes:
    - name: "mongo-data"
      emptyDir: {}
  containers:
    - image: mongo:latest
      name: mongo-data
      volumeMounts:
        - mountPath: "/data"
          name: "mongo-data"
      ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP

 




 
