apiVersion: v1
kind: Pod
metadata:
  name: mongo-data
spec:
  volumes:
    - name: "mongo-data"
      emptyDir: {}
  containers:
    - image: mongo:latest
      name: mongo-data
      volumeMounts:
        - mountPath: "/data"
          name: "mongo-data"
      ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP
      env:
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: cm
              key: mongo_db_name
        - name: MONGO_TESTVAL
          value: {{ .Values.mongo.testval }} 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-data
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
 




 
